#global:
#  scrape_interval: 15s
#
#scrape_configs:
#  - job_name: 'kafka'
#    static_configs:
#      - targets:
#          - 'kafka-1:19092'
#          - 'kafka-2:19093'
#          - 'kafka-3:19094'
#  - job_name: 'kafka-exporter'
#    static_configs:
#      - targets:
#          - 'kafka-exporter:9308'

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets:
          - 'kafka-exporter:9308'